language: node_js
node_js:
  - 12

services:
  - postgresql

env:
  - DATABASE_URL='postgresql://postgres@localhost:5432/users'

before_script:
  - psql -c 'create database users;' -U postgres
  - psql -U postgres -d users -a -f waiters.sql